chores + check that postContentApiUrl is defined + remove need for deeplinkFlowId cookie
serlo/ece-as-a-service pull request #209
Opened 2023-02-15 10:28 UTC by kulla

2023-02-16 17:02 UTC, LarsTheGlidingSquirrel requested changes
Added some additional notes for improvements, see below.

Awesome that we now can omit setting another cookie and the code looks more clean now. :+1: 

In my local test environment, I still got an error message: "Die Kommunikation mit dem Remote-System konnte nicht verifiziert werden". Can we be sure that this error does not happen in the production environment? 
![image](https://user-images.githubusercontent.com/59921805/219435387-e03a6295-4dd3-402b-a6c4-391f71122bb7.png)

2023-02-20 12:35 UTC, kulla commented on src/backend/server.ts
> +const deeplinkFlowMaxAge = 20
Good catch :smile: -> I changed it to 45min

2023-02-20 12:35 UTC, kulla commented on src/backend/server.ts
> +    if (!verifyResult.success) return
This is done by the `verifyJWT()` method

2023-02-20 12:42 UTC, kulla commented
> In my local test environment, I still got an error message: "Die Kommunikation mit dem Remote-System konnte nicht verifiziert werden". Can we be sure that this error does not happen in the production environment?

BTW: We need to ask Daniel how we can fix this. I also have it

2023-02-20 12:45 UTC, kulla commented on src/backend/server.ts
> +    if (!verifyResult.success) return
(See https://github.com/serlo/ece-as-a-service/issues/222)

2023-02-20 12:45 UTC, kulla commented on src/backend/server.ts
> +const deeplinkFlowMaxAge = 20
See https://github.com/serlo/ece-as-a-service/issues/222

2023-02-20 13:25 UTC, LarsTheGlidingSquirrel approved these changes

2023-02-20 13:26 UTC, merged